Avoid clash with a macro in ctype.h from OpenBSD
```
error: expected member name or ';' after declaration specifiers
    uint32_t _S[4][256];
    ~~~~~~~~ ^
/usr/include/ctype.h:48:12: note: expanded from macro '_S'
```